name: 'Docker Launcher'
description: 'Launch docker image'
inputs:
  PROJECT_NAME:
    required: true
  DOCKER_IMAGE:
    required: true
  PLATFORM:
    required: true
runs:
  using: "composite"
  steps:
    - name: Launch Container (${{ inputs.DOCKER_IMAGE }})
      env:
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
        DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
        PLATFORM: ${{ inputs.PLATFORM }}
      run: ${{ github.action_path }}/../../scripts/launcher.sh
      shell: bash
