name:
  CI
on:
  [push, pull_request]
jobs:
  test:
    name: Cross Platform Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ["debian-buster", "debian-bullseye", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04"]
        platform: ["linux-arm64", "linux-amd64"]
        exclude:
          - docker_image: "ubuntu-22.04"
            platform: "linux-arm64"
    steps:
      - name: Set up QEMU for cross-platform emulation
        uses: docker/setup-qemu-action@v2
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Launch docker container (${{ matrix.docker_image }})
        uses: Infineon/optiga-tpm-cheatsheet/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          PLATFORM: ${{ matrix.platform }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executed scripts
          path: ${{ matrix.platform }}_${{ matrix.docker_image }}.sh
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          draft: false
          prerelease: false
          files: |
            LICENSE
            ${{ matrix.platform }}_${{ matrix.docker_image }}.sh